In [36]:
import pandas as pd
import numpy as np
robo2data = pd.read_csv('Robot2',delim_whitespace=True,index_col=False)
ran = np.random.rand(len(robo2data)) < 0.8
train = robo2data[ran]
val = robo2data[~ran]
train.to_csv('UsedTrainingDataForRobo2Ds.csv')
val.to_csv('UsedValidationDataForRobo2Ds.csv')
#train.head()
#val.head()
#print(len(train))
#print(len(val))

def NumberOfEachClass(GivenData):
    NumberOfClassZerosInGivenData = 0
    NumberOfClassOnesInGivenData = 0
    for i in list(GivenData.index.values):
        if GivenData.at[int(i),'class'] == 0:
            NumberOfClassZerosInGivenData += 1
        else:
            NumberOfClassOnesInGivenData += 1
    print('NumberOfClassZerosInGivenData '+str(NumberOfClassZerosInGivenData))
    print('NumberOfClassOnesInGivenData  '+str(NumberOfClassOnesInGivenData))
    print('Class Zeros Percentage '+str(NumberOfClassZerosInGivenData/(NumberOfClassZerosInGivenData+NumberOfClassOnesInGivenData)))
    print('Class Ones Percentage '+str(NumberOfClassOnesInGivenData/(NumberOfClassZerosInGivenData+NumberOfClassOnesInGivenData)))
#NumberOfEachClass(train)
#NumberOfEachClass(val)
import math 
def  getDistBetweenPoints(Point1,Point2,method):
    #print(Point1)
    #print(Point2)
    if method == 'Euclidean':
        sum = 0
        for i in range(0,len(Point1)-1):
            sum = sum + (abs(Point1[i] - Point2[i]))**2
        #print("Distance between Point1 and Point 2 is")
        #print(Point1)
        #print(Point2)
        #print(sum**(1/float(2)))
        return sum**(1/float(2))
    #if method ==
def getDistanceFromAllPoints(Point,distance_method):
    DistancesFromAllOtherPoints ={}
        #for i in list(train['Id']):
            #DistancesFromAllOtherPoints{i} = 
    for index,row in train.iterrows():
        if row[-1] != Point[-2]:
            DistancesFromAllOtherPoints[row[-1]] = [getDistBetweenPoints(list(row),Point,distance_method),row[0]]
    #print(DistancesFromAllOtherPoints)
    return DistancesFromAllOtherPoints
def getLabel(Point,distance_method,NumOfNeighbours):
    NearestNeighboursAndTheirDistances = {}  
    DistancesFromAllOtherPoints = getDistanceFromAllPoints(Point,distance_method)
    NearestNeighboursAndTheirDistances = {k: DistancesFromAllOtherPoints[k] for k in list(DistancesFromAllOtherPoints)[:NumOfNeighbours]}
    print(len(DistancesFromAllOtherPoints))
    #print(NearestNeighboursAndTheirDistances)
    for key, value in DistancesFromAllOtherPoints.items():
        for key1, value1 in NearestNeighboursAndTheirDistances.items():
            if value[0] <= value1[0]:# and key != key1:
                del NearestNeighboursAndTheirDistances[key1]
                NearestNeighboursAndTheirDistances[key] = value
                break
            #elif value[0] == value1[0]:
    NumberOfClassZero = 0
    NumberOfClassOne = 0
    print(Point)
    print(NearestNeighboursAndTheirDistances)
    
    for key, value in NearestNeighboursAndTheirDistances.items():
        if NearestNeighboursAndTheirDistances[key][1] == 1:
            NumberOfClassOne += 1
        else:
            NumberOfClassZero += 1    
    if(NumberOfClassOne>NumberOfClassZero):
        return 1
    else:
        return 0          
def compute(GivenDataSet,distance_method,NumOfNeighbours):
    GivenDataSet["predict"] = [0]*len(val)
    for index,row in GivenDataSet.iterrows():
        GivenDataSet.at[int(index),'predict'] = getLabel(row.tolist(),distance_method,NumOfNeighbours)
    #caluculate accuracy and precision
    #return GivenDataSet
def CalulatePrecsionRecallEtc(GivenTestData):
    TN = 0
    FP = 0
    FN = 0
    TP = 0
    for i in list(GivenTestData.index.values):
        if str(GivenTestData.at[i,'class']) == str(1) and str(GivenTestData.at[i,'predict']) == str(1):
            TP = TP + 1
        elif str(GivenTestData.at[i,'class']) == str(1) and str(GivenTestData.at[i,'predict']) == str(0):
            FN = FN + 1
        elif str(GivenTestData.at[i,'class']) == str(0) and str(GivenTestData.at[i,'predict']) == str(1):
            FP = FP + 1
        elif str(GivenTestData.at[i,'class']) == str(0) and str(GivenTestData.at[i,'predict']) == str(0):
            TN = TN + 1
    print("Results On GivenTestData")
    print("-------------------------------------------------")
    print("True Positive are    "+ str(TP))
    print("True Negatives are   "+ str(TN))
    print("False Positive are   "+ str(FP))
    print("False Negatives are  "+str(FN))
    Precision = (TP/(TP+FP))
    Recall = (TP/(TP+FN))
    F1_Score = 2*((1/Recall)+(1/Precision))
    accuracy = (TN+TP)/(TN+TP+FP+FN)
    print("Precsion is          "+str(Precision))
    print("Recall is            "+str(Recall))
    print("F1_Score is          "+str(F1_Score))
    print("Accuracy is          "+str(accuracy))
    print("-------------------------------------------------")

NumOfNeighbours = 1
distance_method = 'Euclidean'
GivenDataSet = val.copy()
compute(GivenDataSet,distance_method,NumOfNeighbours)
CalulatePrecsionRecallEtc(GivenDataSet)
GivenDataSet

96
[1, 1, 1, 1, 1, 1, 2, 'data_2', 0]
{'data_146': [1.0, 1]}
96
[1, 1, 1, 1, 1, 2, 1, 'data_3', 0]
{'data_145': [1.4142135623730951, 1]}
96
[1, 1, 1, 1, 1, 2, 2, 'data_4', 0]
{'data_28': [1.0, 1]}
96
[0, 1, 1, 2, 2, 4, 2, 'data_40', 0]
{'data_39': [1.0, 0]}
96
[1, 1, 1, 2, 3, 3, 2, 'data_46', 0]
{'data_45': [1.0, 1]}
96
[0, 1, 2, 1, 2, 3, 1, 'data_61', 0]
{'data_203': [1.4142135623730951, 0]}
96
[1, 1, 2, 1, 3, 1, 1, 'data_65', 0]
{'data_209': [1.0, 1]}
96
[1, 1, 2, 1, 3, 1, 2, 'data_66', 0]
{'data_68': [1.0, 1]}
96
[0, 1, 2, 1, 3, 4, 1, 'data_71', 0]
{'data_239': [1.4142135623730951, 0]}
96
[1, 1, 2, 2, 3, 2, 2, 'data_92', 0]
{'data_91': [1.0, 1]}
96
[0, 1, 3, 1, 1, 2, 1, 'data_99', 0]
{'data_123': [1.0, 0]}
96
[1, 2, 1, 2, 3, 1, 2, 'data_186', 0]
{'data_42': [1.0, 1]}
96
[0, 2, 2, 1, 3, 3, 1, 'data_213', 0]
{'data_261': [1.0, 0]}
96
[1, 2, 2, 2, 2, 3, 1, 'data_229', 0]
{'data_230': [1.0, 1]}
96
[1, 2, 3, 1, 1, 3, 1, 'data_245', 0]
{'data_198': [1.4142135623730951, 1]}
96
[0, 2, 3, 2, 1, 2, 2, 'data_268', 0]
{'data_266': [1.0, 0]}
96
[0, 2, 3, 2, 1, 4, 1, 'data_271', 0]
{'data_280': [1.4142135623730951, 0]}
96
[0, 2, 3, 2, 3, 2, 1, 'data_283', 0]
{'data_281': [1.0, 0]}
96
[0, 3, 1, 1, 2, 4, 2, 'data_304', 0]
{'data_328': [1.0, 0]}
96
[1, 3, 1, 2, 3, 1, 1, 'data_329', 0]
{'data_377': [1.0, 1]}
96
[1, 3, 2, 1, 1, 2, 2, 'data_340', 0]
{'data_364': [1.0, 1]}
96
[0, 3, 2, 2, 3, 4, 1, 'data_383', 0]
{'data_239': [1.0, 0]}
96
[1, 3, 3, 1, 1, 3, 2, 'data_390', 0]
{'data_366': [1.4142135623730951, 1]}
96
[1, 3, 3, 1, 1, 4, 1, 'data_391', 0]
{'data_343': [1.4142135623730951, 0]}
96
[0, 3, 3, 1, 3, 2, 1, 'data_403', 0]
{'data_404': [1.0, 0]}
96
[0, 3, 3, 2, 3, 3, 2, 'data_430', 0]
{'data_432': [1.0, 0]}
Results On GivenTestData
-------------------------------------------------
True Positive are    13
True Negatives are   12
False Positive are   0
False Negatives are  1
Precsion is          1.0
Recall is            0.9285714285714286
F1_Score is          4.153846153846153
Accuracy is          0.9615384615384616
-------------------------------------------------

     class  a1  a2  a3  a4  a5  a6        Id  predict
0        1   1   1   1   1   1   2    data_2        1
1        1   1   1   1   1   2   1    data_3        1
2        1   1   1   1   1   2   2    data_4        1
12       0   1   1   2   2   4   2   data_40        0
16       1   1   1   2   3   3   2   data_46        1
20       0   1   2   1   2   3   1   data_61        0
21       1   1   2   1   3   1   1   data_65        1
22       1   1   2   1   3   1   2   data_66        1
26       0   1   2   1   3   4   1   data_71        0
34       1   1   2   2   3   2   2   data_92        1
35       0   1   3   1   1   2   1   data_99        0
59       1   2   1   2   3   1   2  data_186        1
66       0   2   2   1   3   3   1  data_213        0
71       1   2   2   2   2   3   1  data_229        1
74       1   2   3   1   1   3   1  data_245        1
81       0   2   3   2   1   2   2  data_268        0
82       0   2   3   2   1   4   1  data_271        0
86       0   2   3   2   3   2   1  data_283        0
91       0   3   1   1   2   4   2  data_304        0
97       1   3   1   2   3   1   1  data_329        1
98       1   3   2   1   1   2   2  data_340        1
107      0   3   2   2   3   4   1  data_383        0
108      1   3   3   1   1   3   2  data_390        1
109      1   3   3   1   1   4   1  data_391        0
112      0   3   3   1   3   2   1  data_403        0
120      0   3   3   2   3   3   2  data_430        0